# Do NOT update manually; changes here will be overwritten by Copier
_commit: 56ef213
_src_path: /home/mike/ssi-addons-repo-template/
dependency_installation_mode: OCA
generate_requirements_txt: true
include_aeroo_report: false
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: opnsynid-hr-timesheet
repo_name: opnsynid-hr-timesheet
repo_slug: opnsynid-hr-timesheet
travis_apt_packages: []
travis_apt_sources: []

